title: Code Nomad
description: Tales of a Transient Programmer

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/jasonkarns" # the subpath of your site, e.g. /blog

# email: your-email@example.com
twitter_username: jasonkarns
github_username:  jasonkarns

markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
