title: Code Nomad
# email: your-email@example.com
description: Tales of a Transient Programmer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jasonkarns
github_username:  jasonkarns

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

defaults:
  - scope: { path: "", type: posts }
    values:
      layout: default
